### ISSUE TITLE
Eurobodalla Shire Council: Link to more info blocked

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#1]
In this example https://www.planningalerts.org.au/applications/1532739

More information leads to 
"Unauthorised Access Error
You are not authorised to access the requested function. Use your browser's Back feature to return to the previous function."

https://eservices.esc.nsw.gov.au/T1PRProd/WebApps/eProperty/P1Unauthorised.aspx

**Comment by mlandauer** [comment]
Confirmed that this is still happening on recent applications (e.g. https://www.planningalerts.org.au/applications/1692741)

**Comment by mlandauer** [comment]
Previously scraped applications will still have an old url and will not work. However, any new applications scraped should have a URL which works now. Phew.
