### ISSUE TITLE
Inner West: council site has moved

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#10]
Multiple people (including the council themselves) have drawn our attention to the fact that the council has a new website and asked us to update.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2kih1)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2x939)

**Comment by mlandauer** [comment]
From #9 https://innerwest.t1cloud.com/T1Default/CiAnywhere/Web/INNERWEST/Compliance/ApplicationPortalMyEnquiry?f=%24P1.COM.APPLNDAT.ENQ&h=tgLX8GrnDp&t=FB2FF96&suite=PR&pagekey=20200709145804

**Comment by mlandauer** [comment]
New scraper is at https://github.com/planningalerts-scrapers/multiple_cianywhere
