### ISSUE TITLE
Wollondilly Shire Council: No data received since 24 Jun 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#105]
This issue has been **automatically** created by PlanningAlerts for [Wollondilly Shire Council](http://www.planningalerts.org.au/authorities/wollondilly_shire)

It uses the scraper [planningalerts-scrapers/multiple_civica](https://morph.io/planningalerts-scrapers/multiple_civica)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by mlandauer** [comment]
Looks like their civica system has completely dissapeared. That's the bad news. It looks like they have a new custom system at https://tracking.wollondilly.nsw.gov.au/. That would normally be very bad news. However, this system actually looks quite good. It's simple and fast and does the job. It also has an api so getting the data out should be straightforward.

**Comment by mlandauer** [comment]
From https://www.wollondilly.nsw.gov.au/home/mediareleases/council-launches-new-online-da-tracker/
> “This system is user friendly and easy to navigate. Even better, it was developed in-house by Council, so it is at no extra cost to ratepayers.”

Much kudos to Wollondilly Shire Council for doing this and doing it well.

**Comment by mlandauer** [comment]
@katska is going to call them to congratulate them and see if we can talk to the people that made this!

**Comment by katska** [comment]
@matthew I'll call them when we've added it to PlanningAlerts

**Comment by mlandauer** [comment]
This is all working now. So closing!
