### ISSUE TITLE
Gladstone Regional Council: No data received since 20 Nov 2019

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#151]
This issue has been **automatically** created by PlanningAlerts for [Gladstone Regional Council](http://www.planningalerts.org.au/authorities/gladstone)

It uses the scraper [planningalerts-scrapers/multiple_masterview](https://morph.io/planningalerts-scrapers/multiple_masterview)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by katska** [comment]
There are no applications currenly on display. https://www.gladstone.qld.gov.au/directory-record/70/no-applications-currently-on-display

**Comment by mlandauer** [comment]
> There are no applications currenly on display. https://www.gladstone.qld.gov.au/directory-record/70/no-applications-currently-on-display

But we don't want to scrape this special page. We want to scrape the epathway system instead as we already have a scraper for that ready to go.

**Comment by mlandauer** [comment]
Looks like adding the new scraper in epathway didn't work for some reason

**Comment by mlandauer** [comment]
Sigh. It looks like I forgot to update the scraper info in PlanningAlerts :-( That's fixed now
