### ISSUE TITLE
South Australian Planning Portal: Has it replaced information from some local councils?

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#157]
There are currently many broken scrapers for local authorities in South Australia. Is this because activity has moved to the Planning Portal?

**Comment by katska** [comment]
https://www.saplanningportal.sa.gov.au/planning_reforms https://www.saplanningportal.sa.gov.au/updates/news_item?a=691752 ?

**Comment by mlandauer** [comment]
The answer is yes and as of the end of march all applications in south australia have to go through the planning portal
