### ISSUE TITLE
SA Planning Portal: Wrong fields loaded to database - address particularly

### ISSUE THREAD

**Issue by softgrow** [planningalerts-scrapers/issues#159]
Recent loading into the database has the fields confused, e.g. the last line of the CSV is line 6112, ID 68673 along with the last 100 or so since 1 August (and a few before) has the following errors:

- address field is "Anthony Masone, SA" but should be "32 Gray Street Tranmere"
- description field is "CAMPBELLTOWN CITY COUNCIL" but should be "Division of land into 2 new Torrens Title allotments"
- info_url field is "http://www.saplanningportal.sa.gov.au/public_register" should be "https://plan.sa.gov.au/development_application_register#view-68673-LDE"
- comment_url field is "http://www.saplanningportal.sa.gov.au/public_register" should be "https://plan.sa.gov.au/development_application_register"

**Comment by mlandauer** [comment]
@MichaelBone any chance you could take a look?

**Comment by MichaelBone** [comment]
Corrected the index numbers used when extracting data (the index numbers have changed since this scraper was originally written).  See commit 3c70d19154ca298c1bb6fd32b3f2a78d428b8f23
