### ISSUE TITLE
Zombie Sa Planning Portal scraper running on morph.io

### ISSUE THREAD

**Issue by softgrow** [planningalerts-scrapers/issues#161]
In trying to raise issue #159 I was confused by the presence of two scrapers for the SA Planning portal running on morph.io.

In particular https://morph.io/LoveMyData/saplanningportal runs every day but never scrapes any data and has been superseded. Can it be turned off please?

**Comment by mlandauer** [comment]
It's perfectly normal for there to be multiple versions of a scraper running on morph.io. The urls for the scraper are namespaced by the owner of the scraper. It follows a similar model as Github.

So, closing this as a "won't fix".
