### ISSUE TITLE
Frankston: Condition 1 plans refer to previously-approved applications

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#18]
We've had advice from Frankston Council that applications with codes matching "XXX/YYYY/P/A" are "Condition 1 plans" which need to be approved by council - but relate to an earlier application "XXX/YYYY/P", which has already been approved. 

_nb: looking at recent search results, it looks like the last part ("/A") can match any letter from at least A to D. All the results I've seen have "Condition 1" as the first part of the description, so if we do want to detect these we probably want to look for "/P(/?)" in the reference, or "^Condition 1" in the description._

There's no window for public feedback on these "Condition 1 plans". When people provide feedback, the council responds to tell them that the application we told them only appeared on the council's website yesterday (because that's when we saw the "/A" appear) was approved a long time ago (because they're thinking of the non-"/A" version) which confuses the commentor and makes it look as though we're sending late notifications.

In keeping with PA principles, I would suggest we allow comments and forward them to councils. In order to set people's expectations though, I think it would make sense to display the "Notification period has already passed" banner on these applications, as we know that the window has indeed passed.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_26h51)

**Comment by mlandauer** [comment]
This is just too messy for words. I do think what is suggested in openaustralia/planningalerts#267 is a good idea where you can easily see previous applications for the same address but doing anything specific just for the one authorities specific numbering scheme seems a bit crazy to me. So, closing this as a "won't fix"
