### ISSUE TITLE
New data is being scraped, but is not being added to the database

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#20]
The logs on https://morph.io/planningalerts-scrapers/KingboroughCouncil show data being scraped:

````
Saving record DA-2019-195 - 27 Garnett Street, Blackmans Bay, Tasmania
 Saving record DA-2019-249 - 'Alderley' , 290 Tinderbox Road, Tinderbox, Tasmania
 Saving record DA-2019-106 - 10 Dolphin Drive, Kingston, Tasmania
````

The fork of the scraper at https://morph.io/jamezpolley/KingboroughCouncil is able to save data into the database.

But quering the API on this scraper doesn't show the newly-scraped records - in fact, nothing from 2017 onwards

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_uf9h)

**Comment by mlandauer** [comment]
Duplicate of #85
