### ISSUE TITLE
nothing changed in the database

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/issues#22]
After merging planningalerts-scrapers/KingboroughCouncil#2 the scraper is reporting that it's collecting data but morph says, `nothing changed in the database`. I'm guessing it's to do with the [potential issue flagged](https://github.com/planningalerts-scrapers/KingboroughCouncil/pull/2#issue-241691674) in the PR:

>HOWEVER...... You need to nuke the database on morph first because I am now saving extra column called 'on_notice_from' and it wasn't available before.

I really don't think nuking the database is the solution to adding a new column. I think it would be a better idea to...add a new column :wink:

**Comment by mlandauer** [comment]
I'm going to close this as it sort of seems it was resolved?
