### ISSUE TITLE
City of Prospect: Updated URL

### ISSUE THREAD

**Issue by MichaelBone** [planningalerts-scrapers/issues#23]
The URL for development applications has changed from http://www.prospect.sa.gov.au/developmentregister to http://www.prospect.sa.gov.au/development-register.  See https://morph.io/planningalerts-scrapers/city_of_prospect_sa_development_applications.

**Comment by mlandauer** [comment]
Related to #101

**Comment by mlandauer** [comment]
This fix was made in https://github.com/planningalerts-scrapers/city_of_prospect_sa_development_applications/commit/e6fb8982f415c2a0d86c5b0d21c53c2e300ce7bd
