### ISSUE TITLE
scraper for NT?

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#253]
I noticed this story
https://twitter.com/dameyon/status/1315948182220738560

Then looked on PlanningAlerts and was reminded that there is no scraper for Darwin. In fact nothing from NT in PlanningAlerts.

Their notices are online
https://www.ntlis.nt.gov.au/planning-notices-online/notices#/

**Comment by mlandauer** [comment]
There is. It just hadn't been working for a while. It is now fixed https://github.com/planningalerts-scrapers/northern_territory/blob/master/scraper.rb
