### ISSUE TITLE
Nillumbik Shire Council: No data received since  1 Dec 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#271]
This issue has been **automatically** created by PlanningAlerts for [Nillumbik Shire Council](http://www.planningalerts.org.au/authorities/nillumbik)

It uses the scraper [planningalerts-scrapers/multiple_epathway_scraper](https://morph.io/planningalerts-scrapers/multiple_epathway_scraper)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by rammadogs** [comment]
I've cloned the multiple_epathway_scraper on my machine and it seems to be scraping Nillumbik just fine when I run it on my own laptop but still not working when morph.io runs it.

Morph.io is producing the following error: nillumbik: ERROR: execution expired.

I'll keep investigating but I'm not sure if I can fix this on my end. My best guess is that Nillumbik have blocked morph.io's IP address...

**Comment by mlandauer** [comment]
@rammadogs sounds suspiciously like they're blocking non-australian traffic

**Comment by rammadogs** [comment]
Matthew, I think you’re right. I just used an overseas proxy and couldn’t get onto the planning portal. Thank you! 😊

**Comment by mlandauer** [comment]
@rammadogs ridiculous, right? It's now happening regularly enough with council websites that we've added a feature to most of the scrapers - https://github.com/planningalerts-scrapers/multiple_epathway_scraper/commit/0a28d9fc1d1e7cd45034710cbfccabb3beca7a21

Anyway, it's fixed it here which is great

**Comment by rammadogs** [comment]
Ah, brilliant, thanks for fixing it. Yep, totally ridiculous. I wonder why they’re doing it!
