### ISSUE TITLE
Mid-Coast Council (Greater Taree): No data received since  5 Dec 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#273]
This issue has been **automatically** created by PlanningAlerts for [Mid-Coast Council (Greater Taree)](http://www.planningalerts.org.au/authorities/greater_taree)

It uses the scraper [planningalerts-scrapers/multiple_icon](https://morph.io/planningalerts-scrapers/multiple_icon)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ebet)

**Comment by katska** [comment]
They've moved to a new system. Here's a URL pointing to their new system
https://midcoast-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/eTrack/eTrackPropertyDetails.aspx?r=MC.WEBGUEST&f=%24P1.ETR.PRPDET.VIW&PropertyNo=1037910

**Comment by mlandauer** [comment]
Related to #276
