### ISSUE TITLE
Cassowary Coast Regional Council

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#277]
please add Cassowary Coast regional council

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39io5)

**Comment by mlandauer** [comment]
Looks like they are on Technology one: https://ccrc-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/PublicNotices/AllPublicNotices.aspx?r=CCRC.WEBGST&f=P1.ESB.PUBNOTAL.ENQ

**Comment by mlandauer** [comment]
New council added. See https://www.planningalerts.org.au/authorities/cassowary_coast/applications
