### ISSUE TITLE
info_url 404s for some applications

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/issues#28]
The `info_url` for [this application](https://www.planningalerts.org.au/applications/654406) 404s: http://www.lgnoticeboardassets.justice.nsw.gov.au/liquor_applications/docs/1-4318158135-Notice.pdf

For other applications it works fine. See https://www.planningalerts.org.au/applications/654452 and http://www.lgnoticeboardassets.justice.nsw.gov.au/liquor_applications/docs/1-4306610979-Notice.pdf

**Comment by mlandauer** [comment]
The NSW liquor, gaming and racing has actually been broken since 2017. So, closing this in favour of #70
