### ISSUE TITLE
Coffs Harbour scraper's broken

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#3]
From Console output of last run 
https://morph.io/planningalerts-scrapers/multiple_icon

scraper.rb:38:in `<main>': There were errors with the following authorities: [:cumberland, :coffs_harbour, :randwick, :boroondara]. See earlier output for details (RuntimeError)

**Comment by mlandauer** [comment]
Coffs has just been fixed. See https://www.planningalerts.org.au/authorities/coffs_harbour. So, closing.
