### ISSUE TITLE
 scraper.rb:18:in `strptime': invalid date (ArgumentError)

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/issues#32]
Skipping already saved record MC17/40
 scraper.rb:18:in `strptime': invalid date (ArgumentError)
 	from scraper.rb:18:in `block in <main>'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
 	from scraper.rb:12:in `each_with_index'
 	from scraper.rb:12:in `<main>'

**Comment by mlandauer** [comment]
Duplicate of #79
