### ISSUE TITLE
Detail url points to wrong application

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/issues#33]
I'm not sure if this is a problem with the scraper, or with the council changing the location of applications or something, but... The info_url for this application https://www.planningalerts.org.au/applications/669758?utm_campaign=view-application&utm_medium=email&utm_source=alerts doesn't isn't for the application described no the PlanningAlerts page. 

Needs further investigation.

**Comment by mlandauer** [comment]
I've just checked a recent application for Melbourne City Council and this doesn't seem to be happening. So, closing.
