### ISSUE TITLE
No longer scraping properly

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/issues#34]
https://www.planningalerts.org.au/authorities/melbourne_city - looks like the scraper no longer wants to work.

@Will-mac do you offhand know if there's a better way to get to these or if there's been any significant changes?

Also neat: http://www.melbourne.vic.gov.au/building-and-development/planning-and-building-services/Pages/planning-alerts.aspx - it actually links back to planningalerts

**Comment by Wjrmc** [comment]
Hi team,

Sorry to see this scraper is no longer working. I'll let the planning team know. I'm following up with the team if there is a better way to get these and will update if I find one.

I'd like to see this data more openly available as raw data, which I will raise with our development team,

Will
________________________________

**Comment by mlandauer** [comment]
Melbourne is working. So, closing this
