### ISSUE TITLE
Canterbury-Bankstown Council: No data received since 29 Jun 2021

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#401]
This issue has been **automatically** created by PlanningAlerts for [Canterbury-Bankstown Council](http://www.planningalerts.org.au/authorities/bankstown)

It uses the scraper [planningalerts-scrapers/bankstown](https://morph.io/planningalerts-scrapers/bankstown)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_466bp)

**Comment by katska** [comment]
"City of Canterbury" DAs are now here https://cbcity.powerappsportals.com/ApplicationsOnExhibition/

and look like this

https://eplanning.cbcity.nsw.gov.au/ApplicationSearch/ApplicationDetails?applicationId=DA-670/2020/A

**Comment by MutazAshhab** [comment]
URL to DA and to application are still the same as the ones provided by @kat here. 

> "City of Canterbury" DAs are now here https://cbcity.powerappsportals.com/ApplicationsOnExhibition/
> 
> and look like this
> 
> https://eplanning.cbcity.nsw.gov.au/ApplicationSearch/ApplicationDetails?applicationId=DA-670/2020/A

The issue seems to be with morph.

**Comment by mlandauer** [comment]
Looks like another php problem on morph.io . Ugh.
