### ISSUE TITLE
Yarra: Link to the advertisted applications search rather than the broader applications search

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#41]
As an example, https://www.planningalerts.org.au/applications/1120787 links to https://www.yarracity.vic.gov.au/planning-application-search?applicationNumber=PLN18/0916 - however, this search page does not have a link to let the user do anything with the application.

If we linked to https://www.yarracity.vic.gov.au/services/planning-and-development/planning-applications/advertised-planning-applications?q=PLN18%252f0916 the search result list has a link through to the application in question.

However: it looks like that second page doesn't list applications until they're "Advertised"; while we scrape them as soon as they appear on the page. I've opened planningalerts-scrapers/issues#40 to suggest that perhaps we should only scrape advertised applications, which would make this simpler.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_mdlx)

**Comment by mlandauer** [comment]
Closing this as a "won't fix". I think what we do right now is okay.
