### ISSUE TITLE
Use DA Finder feed?

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/issues#43]
I was interested in what the [official DA Finder app](http://www.planning.act.gov.au/development_applications/da_finder_app) used so I did a packet capture, it's http://api.swelldesign.com.au/dafinder/da/?feed=json

I'm not sure if it's got better data than we're already getting though.

**Comment by mlandauer** [comment]
As far as I know the ACT scraper works okay. So, closing this.
