### ISSUE TITLE
Waverley Council: No data received since 29 Oct 2021

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#455]
This issue has been **automatically** created by PlanningAlerts for [Waverley Council](https://www.planningalerts.org.au/authorities/waverley)

It uses the scraper [planningalerts-scrapers/multiple_icon](https://morph.io/planningalerts-scrapers/multiple_icon)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_46i4l)

**Comment by katska** [comment]
Waverley has moved to the NSW Planning Portal and the URL where we looked DAs at before is not longer available. See https://www.waverley.nsw.gov.au/building/development_applications
