### ISSUE TITLE
Northern Territory Lands Group: No data received since 29 Nov 2021

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#464]
This issue has been **automatically** created by PlanningAlerts for [Northern Territory Lands Group](https://www.planningalerts.org.au/authorities/northern_territory)

It uses the scraper [planningalerts-scrapers/northern_territory](https://morph.io/planningalerts-scrapers/northern_territory)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by tseyiokorodudu** [comment]
I have looked at the scraper, and I think it works fine. The [URL](https://www.ntlis.nt.gov.au/planning-notices-online/notices#/) on the scraper links to the page showing the planning development applications currently on exhibition. Currently, there are no applications being exhibited. I think this is the reason the scraper has not scraped new records. 
The[ planning developments archive](https://www.ntlis.nt.gov.au/planning-notices-online/notices/#/archived) shows that 10/12/2021 was the last day they exhibited an application. And that matches the "on-notice-to" date on the last couple of records scraped by Morph.
