### ISSUE TITLE
Penrith City Council: No data received since 12 Jan 2022

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#495]
This issue has been **automatically** created by PlanningAlerts for [Penrith City Council](https://www.planningalerts.org.au/authorities/penrith)

It uses the scraper [planningalerts-scrapers/multiple_icon](https://morph.io/planningalerts-scrapers/multiple_icon)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by MutazAshhab** [comment]
@mlandauer This has been fixed, could you close it?
