### ISSUE TITLE
Parramatta: Migrate from custom scraper to icon scraper

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#56]
We can't do this at the moment because the icon scraper depends on the "xml" output option which looks to be broken on the Parramatta site. Sigh.

Try this URL for example:
http://eplanning.parracity.nsw.gov.au/Pages/XC.Track/SearchApplication.aspx?d=thismonth&k=LodgementDate&t=%23437&o=xml

We just get "Error - An error has occurred in the application. We apologise for the inconvenience. Please try again."

**Comment by katska** [comment]
person to talk to is Daniel. They are in a meeting. Left a message for them to call me back.

**Comment by mlandauer** [comment]
Done
