### ISSUE TITLE
Banyule City Council: No data received since 16 May 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#60]
This issue has been **automatically** created by PlanningAlerts for [Banyule City Council](http://www.planningalerts.org.au/authorities/banyule)

It uses the scraper [planningalerts-scrapers/banyule](https://morph.io/planningalerts-scrapers/banyule)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by CloCkWeRX** [comment]
```
/app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:937:in `open'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:915:in `start'
```

**Comment by CloCkWeRX** [comment]
https://www.banyule.vic.gov.au/Planning-building/Review-local-planning-applications/Planning-applications-on-public-notice is the new URL.

Legalise:
> Under the Privacy and Data Protection Act 2014 you may not collect the names, addresses and other information of applicants in this register to identify and market products or services to them. By continuing to view applications, you are accepting the conditions of use.
