### ISSUE TITLE
Ipswich City Council: No data received since 18 Jun 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#66]
This issue has been **automatically** created by PlanningAlerts for [Ipswich City Council](http://www.planningalerts.org.au/authorities/ipswich)

It uses the scraper [planningalerts-scrapers/multiple_masterview](https://morph.io/planningalerts-scrapers/multiple_masterview)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by katska** [comment]
Looks like PDonline is online https://pdonline.brisbane.qld.gov.au/MasterViewUI/Modules/ApplicationMaster/default.aspx?page=found&1=lastweek&6=F 
Or am I missing something?
