### ISSUE TITLE
Write new Greenlight scraper for Bellingen

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#68]
This issue has been **automatically** created by PlanningAlerts for [Bellingen Shire Council](http://www.planningalerts.org.au/authorities/bellingen)

It uses the scraper [planningalerts-scrapers/multiple_masterview](https://morph.io/planningalerts-scrapers/multiple_masterview)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by katska** [comment]
to be more specific "Development Application (DA) Tracking
The DA tracking service is currently unavailable.

Council is currently working on providing a new online tool to track development applications which will be available in late 2019.

If you have any questions regarding a development application please contact Customer & Business Services by telephone on 02 6655 7300 during business hours." 
https://www.bellingen.nsw.gov.au/development/development-application-da-tracking

**Comment by mlandauer** [comment]
As far as I can tell the authority is still not receiving data on PlanningAlerts. So, this issue shouldn't be closed. So, reopening

**Comment by mlandauer** [comment]
Wow they still don't have a new system :-( They're only publishing PDFs

**Comment by katska** [comment]
They're publishing the information on their website directly now
https://www.bellingen.nsw.gov.au/development/public-exhibition

**Comment by mlandauer** [comment]
Looks like they have a new system now! See https://bellingen.greenlightopm.com/ This looks doable. Also looks a little familiar. I wonder if this system is being used elsewhere and whether we've written a scraper before.

**Comment by mlandauer** [comment]
Also looks to be used for:
* Horsham Rural City Council https://hrcc.greenlightopm.com/
* Mount Alexander Shire Council https://planning.mountalexander.vic.gov.au/OPMExt/public/main.aspx
* Ararat Rural City Council https://ararat.greenlightopm.com/planning 
* Hobsons Bay City Council https://www.hobsonsbay.vic.gov.au/Services/Planning-Building/Find-a-planning-application-in-Greenlight
(I found these by googling greenlightopm - there's bound to be a bunch more)

I think we should write another scraper to handle all of these

**Comment by mlandauer** [comment]
The [news](https://www.e-vis.com.au/news) page of the people that make greenlight OPM appears to give a list of councils that are using greenlight:
* Pyrenees Council - https://pyrenees.greenlightopm.com/planning
* Golden Plains Shire Council - https://goldenplains.greenlightopm.com/search-advertising?appTypeID=1
* Swanhill Rural City Council - https://swanhill.greenlightopm.com/search-register?deptName=Planning
* Gannawarra Shire Council - https://gannawarra.greenlightopm.com/search-register?deptName=Planning
* Horsham Rural City Council - https://hrcc.greenlightopm.com/search-advertising?appTypeID=1
* Ararat Rural City Council - https://ararat.greenlightopm.com/search-advertising?appTypeID=1
* Bellingen Shire Council - https://bellingen.greenlightopm.com/search-advertising?appTypeID=1
* Hobson Bay City Council - https://hbcc.greenlightopm.com/search-advertising?appTypeID=1
* Kempsey Shire Council - https://kempsey.greenlightopm.com/search-advertising?appTypeID=1
* West Wimmera Shire Council - https://westwimmera.greenlightopm.com/search-advertising?appTypeID=1

The following seem to be using greenlight OPM but not for development applications:
* City of Greater Bendigo - https://bendigo.greenlightopm.com/
* Hindmarsh Shire Council - https://hindmarsh.greenlightopm.com/

I can't seem to find how these are using Greenlight OPM. Maybe it's not ready and public yet:
* Mildura Rural City Council
* Buloke Shire Council

**Comment by mlandauer** [comment]
Found one more by googling "greenlightopm":
* Moorabool Shire Council - https://moorabool.greenlightopm.com/search-register?deptName=Planning

**Comment by katska** [comment]
nice find!

**Comment by mlandauer** [comment]
Finally fixed by moving over to new greenlight scraper
