### ISSUE TITLE
Lane Cove Council: No data received since 24 Oct 2019

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#71]
This issue has been **automatically** created by PlanningAlerts for [Lane Cove Council](http://www.planningalerts.org.au/authorities/lane_cove)

It uses the scraper [planningalerts-scrapers/lane_cove](https://morph.io/planningalerts-scrapers/lane_cove)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by CloCkWeRX** [comment]
http://ecouncil.lanecove.nsw.gov.au/trim/advertisedDAs.aspx is the URL.

```
scraper.rb:40:in `block in <main>': Unexpected type: h2 <h2> (RuntimeError)
					GREENWICH
						<a name="GREENWICH" id="GREENWICH">
					</a>
				</h2>
	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
	from scraper.rb:16:in `<main>'
```

https://github.com/planningalerts-scrapers/lane_cove/blob/master/scraper.rb#L16


Should be an easy fix

**Comment by mlandauer** [comment]
Actually it looks like they're using civica. So, would be good to merge this authority into that scraper. Less scrapers to maintain and all that.

**Comment by mlandauer** [comment]
Here's a URL: http://ecouncil.lanecove.nsw.gov.au/eservice/dialog/daEnquiryInit.do?doc_type=8&nodeNum=2807

**Comment by mlandauer** [comment]
That's fixed things. So closing this. Will also now archive and the old scraper
