### ISSUE TITLE
City of Burnside: No data received since 19 May 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#73]
This issue has been **automatically** created by PlanningAlerts for [City of Burnside](http://www.planningalerts.org.au/authorities/burnside)

It uses the scraper [planningalerts-scrapers/burnside](https://morph.io/planningalerts-scrapers/burnside)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by CloCkWeRX** [comment]
```
Parsing document: https://www.burnside.sa.gov.au/files/assets/public/planning-amp-business/development/planning-amp-building/planning-applications-register/2015/july_2015_01.07.15_-_31.07.15.pdf
Error: Removed API method: PDFDocumentLoadingTask.then, use the `promise` getter instead.
    at PDFDocumentLoadingTask.then (/app/node_modules/pdfjs-dist/build/pdf.js:1309:13)
```

**Comment by mlandauer** [comment]
Actually. It looks like they now have a Technology One Application Tracker. See https://eservices.burnside.sa.gov.au/eProperty/P1/eTrack/eTrackApplicationSearch.aspx?r=P1.WEBGUEST&f=%24P1.ETR.SEARCH.ENQ. In the effort of supporting fewer scrapers it would be good to move this council over to that.

**Comment by mlandauer** [comment]
That fixed it. Now, to archive the old scraper
