### ISSUE TITLE
Surf Coast Shire Council

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#74]
This issue has been **automatically** created by PlanningAlerts for [Surf Coast Shire Council](http://www.planningalerts.org.au/authorities/surf_coast_shire)

It uses the scraper [planningalerts-scrapers/surf_coast](https://morph.io/planningalerts-scrapers/surf_coast)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by mlandauer** [comment]
Still looks like they're on the same (or similar) custom system. Maybe the URL has changed or something? You can see the system at https://eplanning.surfcoast.vic.gov.au/Public/PlanningRegister.aspx?search=basic which looks like a different url to the one that is in the scraper

So, this might be an easy fix.

**Comment by MutazAshhab** [comment]
After visiting https://eplanning.surfcoast.vic.gov.au/Public/PlanningRegister.aspx?search=basic you'll have to accept a privacy policy.

Here is a snippet for that:
```ruby
# agreeing to privacy policy
form = page.forms.first
raise "Form not found" if form.nil?

agree_button = form.button_with(value: "I Agree")
page.form.submit(agree_button)
page = agent.submit(form)
```

After agreeing you'll be redirected to the webpage with the dev applications.
A POST request is made to https://eplanning.surfcoast.vic.gov.au/Services/ReferenceService.svc/Get_PlanningRegister
Javascript is used to populate the table body.

To get the dev applications this scraper must reverse engineer an API call.
To make a request to the API you'll need a cookie.

**Comment by katska** [comment]
@mlandauer surf coast council have been in touch asking about this also. Can it be fixed?

**Comment by mlandauer** [comment]
It turns out surf coast is using the same system as stonnington: https://github.com/planningalerts-scrapers/stonnington

So we should probably combine the two scrapers. However it looks like there's an "export list" button which probably makes getting the data a whole lot easier rather than trying to reverse engineer the API. So, it looks like it's probably worth writing a brand new scraper based loosely on the existing stonnington scraper which uses that button.

**Comment by mlandauer** [comment]
I think I'll just have a go at building a scraper from scratch using the stonnington one as a guide. It doesn't seem worth trying to create a "multiple" scraper for only 2 authorities. Doing one by hand is also a useful starting point for generalising if we decide to go down that path.
