### ISSUE TITLE
Launceston City Council: No data received since  3 Apr 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#75]
This issue has been **automatically** created by PlanningAlerts for [Launceston City Council](http://www.planningalerts.org.au/authorities/launceston)

It uses the scraper [planningalerts-scrapers/launceston](https://morph.io/planningalerts-scrapers/launceston)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3aeit)

**Comment by dcalde** [comment]
http://api.launceston.tas.gov.au/planning/planningAlerts.ashx ... 404

I have emailed planning.queries AT launceston.tas.gov.au to advise of new url.

Otherwise update scraper to get data from here instead: 
https://onlineservice.launceston.tas.gov.au/eProperty/P1/PublicNotices/AllPublicNotices.aspx?r=P1.LCC.WEBGUEST&f=%24P1.ESB.PUBNOTAL.ENQ

**Comment by dcalde** [comment]
PR to fix https://github.com/planningalerts-scrapers/launceston/pull/2

**Comment by mlandauer** [comment]
They're using Technology One (we have already have a scraper for that) but it looks like the search function for finding recent applications is just plain broken - there are recent applications but when you say "all applications in last 28 days" you get an empty list. Great!

**Comment by mlandauer** [comment]
Thanks @dcalde so much for your PR. I'm really sorry it's taken **so long** for this to get merged.
