### ISSUE TITLE
Redland city council - MCUs are not shown in planning alerts

### ISSUE THREAD

**Issue by canesesmarjf** [planningalerts-scrapers/issues#765]
I was looking at recent Material change of use applications to the council and I noticed that although they exist on the council's website, they do not appear on planning alerts. For example, on one of my walks I noticed a new development and I searched on the councils developemnt i website: MCU21/0018 (32 Valantine Road Birkdale 4159) however, this application does not appear on planning alerts. Is this a bug? or does plannign alers ignore these?

**Comment by mlandauer** [comment]
These should now be appearing as we've recently moved over to a new scraper for Redland City Council. See for example https://www.planningalerts.org.au/applications/3010349
