### ISSUE TITLE
Casey City Council

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#788]
This issue has been **automatically** created by PlanningAlerts. Only close this issue once the authority is working again on PlanningAlerts.

**Comment by katska** [comment]
Potential quick win.

They've moved the applications to a T1 cloud service. If I take the URL where Planning Alerts used to find applications and replace the first part of the path with the location of current services, that forms a valid current path:

https://casey-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/eTrack/eTrackApplicationDetails.aspx?ApplicationId=PA22-0707&f=%24P1.ETR.APPDET.VIW&r=P1.WEBGUEST

Current Applications on notice are at https://casey-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/PublicNotices/AllPublicNotices.aspx?r=P1.WEBGUEST&f=P1.CSY.PUBNOTAL.ENQ

An old application path from Planning Alerts was shown at https://eproperty.casey.vic.gov.au/T1PRProd/WebApps/eProperty/P1/eTrack/eTrackApplicationDetails.aspx?ApplicationId=PA22-0707&f=%24P1.ETR.APPDET.VIW&r=P1.WEBGUEST
 

Another note: All the links to DAs on City of Casey's website such as recently submitted DAs, last 7, 28 days,

![Image](https://github.com/planningalerts-scrapers/issues/assets/1001129/cd92fac2-733a-4d49-96df-67ab98eda142)

 etc all work, but the link to "All Applications" still points to https://eproperty.casey.vic.gov.au/T1PRProd/WebApps/eProperty/P1/eTrack/eTrackApplicationSearch.aspx?f=%24P1.ETR.SEARCH.ENQ&Custom=Yes&ApplicationId=P and is broken.



Error for this scraper when it runs on morph 
```

 casey: ERROR: Failed to open TCP connection to eproperty.casey.vic.gov.au:443 (getaddrinfo: Name or service not known)
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:935:in `connect'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
 /app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:915:in `start'
 /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
 /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
 /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
 /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
 /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
 /app/lib/technology_one_scraper.rb:67:in `scrape_period'
 /app/lib/technology_one_scraper.rb:18:in `scrape'
 scraper.rb:14:in `block in scrape'
 scraper.rb:10:in `each'
 scraper.rb:10:in `scrape'
 scraper.rb:30:in `<main>'
```
