### ISSUE TITLE
closest first sort shows older of two DAs for one exact address 

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#808]
closest first sort shows older of two DAs for one exact address - when I'd still expect to see the newest one first at that same address. That's confusing. If that's not an error be clear what is being shown, if closest first consistently shows them oldest first in this sort, then say 'oldest first' or indicate with some visually consistent presentation of the most search recent result. Why? Because that's what people are most often looking for.

for example 
[211 Kelly St, Scone 2337 NSW 
](https://www.planningalerts.org.au/applications/address?q=211+Kelly+St%2C+Scone+2337+NSW+&sort=distance)

<img width="1134" alt="Screenshot 2023-08-09 at 12 17 52 pm" src="https://github.com/planningalerts-scrapers/issues/assets/1001129/887a52ad-b986-44d0-bb7c-fcb66631e0fa">

**Comment by mlandauer** [comment]
@katska this issue should be on openaustralia/planningalerts.

**Comment by katska** [comment]
@mlandauer oops! Thanks!

**Comment by katska** [comment]
moved to #1736
