### ISSUE TITLE
City of Tea Tree Gully: No data received since 30 May 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#99]
This issue has been **automatically** created by PlanningAlerts for [City of Tea Tree Gully](http://www.planningalerts.org.au/authorities/teatreegully)

It uses the scraper [planningalerts-scrapers/multiple_civica](https://morph.io/planningalerts-scrapers/multiple_civica)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by mlandauer** [comment]
On the latest run on morph "tea_tree_gully: ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)"

When I ran the scraper locally it seemed to work fine. So, I'm guessing that the certificate has been updated?

Let's see...

**Comment by CloCkWeRX** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=ecouncil.teatreegully.sa.gov.au&hideResults=on&latest

It's valid, but one of the intermediate ones isn't.
![image](https://user-images.githubusercontent.com/365751/88764194-ad981d80-d1b3-11ea-8b49-027e219b4fd9.png)

The certificate expires in a month or so, they'll likely update it soon.

**Comment by CloCkWeRX** [comment]
Emailed their customer service pointing out the problem

**Comment by mlandauer** [comment]
> Emailed their customer service pointing out the problem

Thank you @CloCkWeRX!
